import Head from 'next/head'
import { useAppDispatch } from "../redux/hooks";
import { useEffect } from "react";
import { fetchAllProducts } from "../redux/features/products/productsThunk";

export default function Home() {
  const dispatch = useAppDispatch()
  useEffect(() => {
    dispatch(fetchAllProducts())
  }, [])

  return (
    <div>
      <Head>
        <title>Видита Систем</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <h1>Work!</h1>

    </div>
  )
}
